Brushed output
sahil-kale/MotorController pull request #17
Opened 2021-01-04 22:00 UTC by sahil-kale

2021-01-04 22:02 UTC, sahil-kale commented
Ensure that PWM input is approved first!

2021-01-04 22:16 UTC, AadityaChaudhary requested changes

2021-01-04 22:16 UTC, AadityaChaudhary commented on Core/Inc/PWMinput.hpp
> +#ifndef PWM_INPUT_HPP
why have you defined the input stuff in this output or?

2021-01-04 22:16 UTC, AadityaChaudhary commented on Core/Src/brushed_output.cpp
> +bool BrushedMotorDriver::set(double speed)
logic looks dubious, could you leave a comment explaining this function and how it handles forward/reverse speeds?

2021-01-04 22:16 UTC, AadityaChaudhary commented on Core/Src/PWMinput.cpp
> +#include "tim.h"
why was this needed in this pr? to resolve merge issues with git?

2021-01-05 01:22 UTC, sahil-kale commented on Core/Src/PWMinput.cpp
> +#include "tim.h"
Tim is needed for the timer object definitons

2021-01-05 02:14 UTC, closed without merging