Encoder driver
sahil-kale/MotorController pull request #27
Opened 2021-01-08 07:49 UTC by AadityaChaudhary

added the driver as singleton
added interrupt to handle the signals
added comments to explain the functions and logic
I have some diagrams and notes that would better explain the logic, but i am unsure where to include them, or whether i even should

2021-01-08 07:54 UTC, sahil-kale requested changes
Looks good, add the semicolon on the hpp file though

2021-01-08 07:54 UTC, sahil-kale commented on Core/Inc/EncoderDriver.hpp
> +}
Semicolon 👀

2021-01-09 09:03 UTC, AadityaChaudhary commented on Core/Inc/EncoderDriver.hpp
> +}
added

2021-01-09 22:00 UTC, sahil-kale approved these changes

2021-01-09 22:00 UTC, merged